//! Scenario Generator - Recursive survey wizard for creating scenarios
//!
//! Uses LLM-driven questioning to generate scenario YAML files from
//! natural language descriptions. All navigation works with gamepad.

use std::path::PathBuf;

use super::schema::{
    PermissionPolicy, PermissionType, ProjectConfig, Scenario, ScenarioMeta, SurveyStrategy,
};

/// Start option for the generator wizard
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum StartOption {
    /// Create new scenario from scratch
    New,
    /// Fork an existing scenario
    Fork,
    /// Generate from natural language description
    FromDescription,
}

impl StartOption {
    pub fn all() -> &'static [StartOption] {
        &[StartOption::New, StartOption::Fork, StartOption::FromDescription]
    }

    pub fn label(&self) -> &'static str {
        match self {
            StartOption::New => "New scenario",
            StartOption::Fork => "Fork existing",
            StartOption::FromDescription => "From description",
        }
    }

    pub fn description(&self) -> &'static str {
        match self {
            StartOption::New => "Start fresh with guided questions",
            StartOption::Fork => "Copy and modify an existing scenario",
            StartOption::FromDescription => "Describe what you want in plain English",
        }
    }
}

/// A dynamically generated question option
#[derive(Debug, Clone)]
pub struct QuestionOption {
    /// Short label shown to user
    pub label: String,
    /// Optional longer description
    pub description: Option<String>,
}

impl QuestionOption {
    pub fn new(label: impl Into<String>) -> Self {
        Self {
            label: label.into(),
            description: None,
        }
    }

    pub fn with_description(mut self, desc: impl Into<String>) -> Self {
        self.description = Some(desc.into());
        self
    }
}

/// A question dynamically generated by the LLM
#[derive(Debug, Clone)]
pub struct DynamicQuestion {
    /// The question text
    pub question: String,
    /// Available options to choose from (2-6 typically)
    pub options: Vec<QuestionOption>,
    /// Whether multiple selections are allowed
    pub multi_select: bool,
    /// Optional context explaining why this question matters
    pub context: Option<String>,
}

/// Record of a question and its answer
#[derive(Debug, Clone)]
pub struct QuestionAnswer {
    /// The question that was asked
    pub question: String,
    /// Indices of selected options
    pub selected: Vec<usize>,
    /// The option labels (for reference)
    pub options: Vec<String>,
}

/// Enriched description from AI expansion
#[derive(Debug, Clone)]
pub struct EnrichedDescription {
    /// Full paragraph explaining what should be built
    pub enriched_description: String,
    /// Inferred goals
    pub inferred_goals: Vec<String>,
    /// Likely project type (rust, node, python, etc.)
    pub likely_project_type: String,
    /// Suggested permissions
    pub suggested_permissions: Vec<PermissionType>,
}

/// State machine for the generator wizard
#[derive(Debug, Clone)]
pub enum GeneratorState {
    /// Initial choice: New, Fork, or From Description
    Start {
        selected: usize,
    },

    /// Text input for description
    DescriptionInput {
        text: String,
        cursor: usize,
    },

    /// Scenario file picker for forking
    ForkPicker {
        files: Vec<PathBuf>,
        selected: usize,
    },

    /// AI is enriching the description
    Enriching {
        original: String,
    },

    /// Recursive survey - LLM decides questions dynamically
    Survey {
        /// All Q&A so far
        history: Vec<QuestionAnswer>,
        /// Enriched description (if started from description)
        enriched: Option<EnrichedDescription>,
        /// Current question from LLM
        current_question: DynamicQuestion,
        /// Selected option index (for gamepad nav)
        selected_option: usize,
        /// Selected options for multi-select
        selected_options: Vec<usize>,
    },

    /// LLM is generating based on collected answers
    Generating {
        history: Vec<QuestionAnswer>,
        enriched: Option<EnrichedDescription>,
    },

    /// Preview the generated scenario
    Preview {
        scenario: Scenario,
        scroll_offset: f32,
    },

    /// User providing feedback for regeneration
    Feedback {
        scenario: Scenario,
        feedback_text: String,
        cursor: usize,
    },

    /// Save completed
    Done {
        output_path: PathBuf,
    },
}

impl Default for GeneratorState {
    fn default() -> Self {
        GeneratorState::Start { selected: 0 }
    }
}

/// Scenario generator that drives the wizard flow
#[derive(Debug, Clone)]
pub struct ScenarioGenerator {
    /// Current wizard state
    pub state: GeneratorState,
    /// Output path for the generated scenario
    pub output_path: Option<PathBuf>,
    /// Base scenario (when forking)
    pub base_scenario: Option<Scenario>,
}

impl ScenarioGenerator {
    /// Create a new generator
    pub fn new() -> Self {
        Self {
            state: GeneratorState::default(),
            output_path: None,
            base_scenario: None,
        }
    }

    /// Create a generator starting from a description
    pub fn from_description(description: String) -> Self {
        Self {
            state: GeneratorState::Enriching {
                original: description,
            },
            output_path: None,
            base_scenario: None,
        }
    }

    /// Create a generator to fork an existing scenario
    pub fn fork(scenario: Scenario) -> Self {
        Self {
            state: GeneratorState::Preview {
                scenario: scenario.clone(),
                scroll_offset: 0.0,
            },
            output_path: None,
            base_scenario: Some(scenario),
        }
    }

    /// Create a generator from an existing scenario (alias for fork)
    pub fn from_fork(scenario: Scenario) -> Self {
        Self::fork(scenario)
    }

    /// Set the output path
    pub fn with_output(mut self, path: PathBuf) -> Self {
        self.output_path = Some(path);
        self
    }

    /// Set the output path (mutable variant)
    pub fn set_output_path(&mut self, path: PathBuf) {
        self.output_path = Some(path);
    }

    /// Get the current state
    pub fn current_state(&self) -> &GeneratorState {
        &self.state
    }

    /// Get the current state (mutable)
    pub fn current_state_mut(&mut self) -> &mut GeneratorState {
        &mut self.state
    }

    /// Navigate selection in current state
    pub fn navigate(&mut self, delta: i32) {
        match &mut self.state {
            GeneratorState::Start { selected } => {
                let len = StartOption::all().len();
                *selected = (*selected as i32 + delta).rem_euclid(len as i32) as usize;
            }
            GeneratorState::ForkPicker { files, selected } => {
                if !files.is_empty() {
                    let len = files.len();
                    *selected = (*selected as i32 + delta).rem_euclid(len as i32) as usize;
                }
            }
            GeneratorState::Survey {
                current_question,
                selected_option,
                ..
            } => {
                let len = current_question.options.len();
                if len > 0 {
                    *selected_option =
                        (*selected_option as i32 + delta).rem_euclid(len as i32) as usize;
                }
            }
            _ => {}
        }
    }

    /// Select current option (A button)
    pub fn select(&mut self) -> Option<GeneratorAction> {
        match &mut self.state {
            GeneratorState::Start { selected } => {
                let options = StartOption::all();
                if let Some(option) = options.get(*selected) {
                    return Some(GeneratorAction::StartOptionSelected(*option));
                }
            }
            GeneratorState::ForkPicker { files, selected } => {
                if let Some(path) = files.get(*selected) {
                    return Some(GeneratorAction::ForkFileSelected(path.clone()));
                }
            }
            GeneratorState::Survey {
                current_question,
                selected_option,
                selected_options,
                ..
            } => {
                if current_question.multi_select {
                    // Toggle selection
                    if selected_options.contains(selected_option) {
                        selected_options.retain(|x| x != selected_option);
                    } else {
                        selected_options.push(*selected_option);
                    }
                } else {
                    // Single select - submit answer
                    return Some(GeneratorAction::AnswerSubmitted(vec![*selected_option]));
                }
            }
            GeneratorState::Preview { scenario, .. } => {
                return Some(GeneratorAction::AcceptScenario(Box::new(scenario.clone())));
            }
            _ => {}
        }
        None
    }

    /// Confirm multi-select (Y button or dedicated confirm)
    pub fn confirm_multi_select(&mut self) -> Option<GeneratorAction> {
        if let GeneratorState::Survey {
            selected_options, ..
        } = &self.state
        {
            if !selected_options.is_empty() {
                return Some(GeneratorAction::AnswerSubmitted(selected_options.clone()));
            }
        }
        None
    }

    /// Go back (B button)
    pub fn back(&mut self) -> Option<GeneratorAction> {
        match &self.state {
            GeneratorState::Start { .. } => Some(GeneratorAction::Cancel),
            GeneratorState::DescriptionInput { .. } => {
                self.state = GeneratorState::Start { selected: 2 };
                None
            }
            GeneratorState::ForkPicker { .. } => {
                self.state = GeneratorState::Start { selected: 1 };
                None
            }
            GeneratorState::Survey { history, .. } if !history.is_empty() => {
                Some(GeneratorAction::UndoLastAnswer)
            }
            GeneratorState::Survey { .. } => {
                self.state = GeneratorState::Start { selected: 0 };
                None
            }
            GeneratorState::Preview { .. } => Some(GeneratorAction::RequestFeedback),
            GeneratorState::Feedback { scenario, .. } => {
                self.state = GeneratorState::Preview {
                    scenario: scenario.clone(),
                    scroll_offset: 0.0,
                };
                None
            }
            _ => None,
        }
    }

    /// Handle text input (for description input state)
    pub fn handle_char(&mut self, c: char) {
        match &mut self.state {
            GeneratorState::DescriptionInput { text, cursor } => {
                text.insert(*cursor, c);
                *cursor += 1;
            }
            GeneratorState::Feedback {
                feedback_text,
                cursor,
                ..
            } => {
                feedback_text.insert(*cursor, c);
                *cursor += 1;
            }
            _ => {}
        }
    }

    /// Handle backspace
    pub fn handle_backspace(&mut self) {
        match &mut self.state {
            GeneratorState::DescriptionInput { text, cursor } => {
                if *cursor > 0 {
                    *cursor -= 1;
                    text.remove(*cursor);
                }
            }
            GeneratorState::Feedback {
                feedback_text,
                cursor,
                ..
            } => {
                if *cursor > 0 {
                    *cursor -= 1;
                    feedback_text.remove(*cursor);
                }
            }
            _ => {}
        }
    }

    /// Submit text input (Enter)
    pub fn submit_text(&mut self) -> Option<GeneratorAction> {
        match &self.state {
            GeneratorState::DescriptionInput { text, .. } => {
                if !text.trim().is_empty() {
                    return Some(GeneratorAction::DescriptionSubmitted(text.clone()));
                }
            }
            GeneratorState::Feedback { feedback_text, .. } => {
                if !feedback_text.trim().is_empty() {
                    return Some(GeneratorAction::FeedbackSubmitted(feedback_text.clone()));
                }
            }
            _ => {}
        }
        None
    }

    /// Scroll preview (right stick)
    pub fn scroll_preview(&mut self, delta: f32) {
        if let GeneratorState::Preview { scroll_offset, .. } = &mut self.state {
            *scroll_offset = (*scroll_offset + delta).max(0.0);
        }
    }

    /// Transition to a new state
    pub fn transition(&mut self, new_state: GeneratorState) {
        self.state = new_state;
    }

    /// Build a scenario from collected data
    pub fn build_scenario(
        &self,
        history: &[QuestionAnswer],
        enriched: Option<&EnrichedDescription>,
    ) -> Scenario {
        // Extract information from Q&A history
        let mut goals = Vec::new();
        let mut project_path = String::from("~/projects/new-project");
        let mut permissions = Vec::new();

        // If we have enriched description, use its goals
        if let Some(e) = enriched {
            goals = e.inferred_goals.clone();
            permissions = e.suggested_permissions.clone();
        }

        // Process Q&A to override/add info
        for qa in history {
            let q_lower = qa.question.to_lowercase();

            // Check for goal-related questions
            if q_lower.contains("goal") || q_lower.contains("want to") {
                for &idx in &qa.selected {
                    if let Some(opt) = qa.options.get(idx) {
                        if !goals.contains(opt) {
                            goals.push(opt.clone());
                        }
                    }
                }
            }

            // Check for project path
            if q_lower.contains("project") && q_lower.contains("path") {
                if let Some(&idx) = qa.selected.first() {
                    if let Some(opt) = qa.options.get(idx) {
                        project_path = opt.clone();
                    }
                }
            }

            // Check for permissions
            if q_lower.contains("permission") || q_lower.contains("allow") {
                for &idx in &qa.selected {
                    if let Some(opt) = qa.options.get(idx) {
                        if opt.to_lowercase().contains("cargo") {
                            permissions.push(PermissionType::Cargo);
                        }
                        if opt.to_lowercase().contains("git") {
                            permissions.push(PermissionType::Git);
                        }
                        if opt.to_lowercase().contains("npm") {
                            permissions.push(PermissionType::Npm);
                        }
                        if opt.to_lowercase().contains("network") {
                            permissions.push(PermissionType::Network);
                        }
                    }
                }
            }
        }

        // Ensure we have at least read/write
        if !permissions.contains(&PermissionType::Read) {
            permissions.push(PermissionType::Read);
        }
        if !permissions.contains(&PermissionType::Write) {
            permissions.push(PermissionType::Write);
        }

        Scenario {
            scenario: ScenarioMeta {
                name: if let Some(e) = enriched {
                    e.enriched_description
                        .split('.')
                        .next()
                        .unwrap_or("New Scenario")
                        .to_string()
                } else {
                    "Generated Scenario".to_string()
                },
                description: enriched.map(|e| e.enriched_description.clone()),
                version: "1.0".into(),
                author: None,
                tags: vec!["generated".into()],
            },
            goals,
            steps: vec![],
            permissions: Some(PermissionPolicy {
                allow: permissions,
                deny: vec![PermissionType::RmRf],
                ask_unknown: true,
                max_auto_approvals: Some(50),
            }),
            surveys: Some(SurveyStrategy::Ubj),
            project: ProjectConfig {
                path: project_path,
                init_if_missing: true,
                git_clone: None,
                branch: None,
                template: None,
            },
            capture: None,
            okrs: None,
            requirements: None,
            constraints: None,
        }
    }
}

impl Default for ScenarioGenerator {
    fn default() -> Self {
        Self::new()
    }
}

/// Actions that the generator can produce
#[derive(Debug, Clone)]
pub enum GeneratorAction {
    /// User selected a start option
    StartOptionSelected(StartOption),
    /// User selected a file to fork
    ForkFileSelected(PathBuf),
    /// User submitted a description
    DescriptionSubmitted(String),
    /// User submitted an answer to a question
    AnswerSubmitted(Vec<usize>),
    /// User wants to undo last answer
    UndoLastAnswer,
    /// User accepted the generated scenario
    AcceptScenario(Box<Scenario>),
    /// User wants to provide feedback
    RequestFeedback,
    /// User submitted feedback
    FeedbackSubmitted(String),
    /// User cancelled
    Cancel,
}

/// Prompts for LLM integration
pub mod prompts {
    pub const EXPAND_PROMPT: &str = r#"
Expand this brief description into detailed scenario goals:

User said: "{DESCRIPTION}"

Return JSON with:
{
  "enriched_description": "Full paragraph explaining what should be built",
  "inferred_goals": ["Goal 1", "Goal 2", ...],
  "likely_project_type": "rust" | "node" | "python" | etc,
  "suggested_permissions": ["read", "write", "cargo", ...]
}
"#;

    pub const NEXT_QUESTION_PROMPT: &str = r#"
You are helping generate a Palace scenario. Based on the conversation so far:

User's goal: {ENRICHED_DESCRIPTION}

Questions answered:
{HISTORY}

Decide what to ask next. You can:
1. Ask another clarifying question (return format: "question")
2. Declare you have enough info (return format: "ready")

If asking a question:
- Generate 2-6 options the user can select with a gamepad
- Choose the right format: yes/no, multiple choice, or multi-select
- Keep options concise (gamepad-friendly)

Return JSON:
{
  "action": "question" | "ready",
  "question": "...",
  "options": [{"label": "...", "description": "..."}],
  "multi_select": false,
  "context": "Why this matters..."
}
"#;
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generator_start_state() {
        let gen = ScenarioGenerator::new();
        assert!(matches!(
            gen.current_state(),
            GeneratorState::Start { selected: 0 }
        ));
    }

    #[test]
    fn test_navigation() {
        let mut gen = ScenarioGenerator::new();

        gen.navigate(1);
        if let GeneratorState::Start { selected } = gen.current_state() {
            assert_eq!(*selected, 1);
        } else {
            panic!("Expected Start state");
        }

        gen.navigate(-1);
        if let GeneratorState::Start { selected } = gen.current_state() {
            assert_eq!(*selected, 0);
        }
    }

    #[test]
    fn test_from_description() {
        let gen = ScenarioGenerator::from_description("implement asteroids".into());
        assert!(matches!(
            gen.current_state(),
            GeneratorState::Enriching { .. }
        ));
    }

    #[test]
    fn test_build_scenario() {
        let gen = ScenarioGenerator::new();
        let enriched = EnrichedDescription {
            enriched_description: "Build an asteroids game in Rust with WGPU.".into(),
            inferred_goals: vec!["Working game".into(), "Ship controls".into()],
            likely_project_type: "rust".into(),
            suggested_permissions: vec![PermissionType::Read, PermissionType::Write, PermissionType::Cargo],
        };

        let scenario = gen.build_scenario(&[], Some(&enriched));
        assert_eq!(scenario.goals.len(), 2);
        assert!(scenario.permissions.is_some());
    }
}
