/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package command-line-arguments */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "main.go"

#include <stdlib.h>

// Event types for streaming
#define EVENT_TEXT 0
#define EVENT_TOOL_USE_START 1
#define EVENT_TOOL_USE_INPUT 2
#define EVENT_TOOL_USE_END 3
#define EVENT_THINKING 4
#define EVENT_DONE 5
#define EVENT_ERROR 6
#define EVENT_TOOL_RESULT 7

// Callback type for streaming events
// event_type: one of EVENT_* constants
// data: event-specific data (text chunk, tool name, JSON input, etc.)
typedef void (*stream_callback)(int event_type, const char* data);

// Tool executor callback - returns tool result as C string (caller must free)
// tool_name: name of tool to execute
// tool_input: JSON input for the tool
typedef char* (*tool_executor)(const char* tool_name, const char* tool_input);

// Helper to invoke the callback from Go
static inline void invoke_callback(stream_callback cb, int event_type, const char* data) {
    cb(event_type, data);
}

// Helper to invoke tool executor from Go
static inline char* invoke_tool(tool_executor exec, const char* name, const char* input) {
    return exec(name, input);
}

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern int anthropic_init(char* apiKey);
extern int anthropic_init_with_base(char* apiKey, char* baseURL);
extern char* anthropic_message(char* model, char* systemPrompt, char* userMessage, int maxTokens);
extern void anthropic_message_stream(char* model, char* systemPrompt, char* userMessage, int maxTokens, stream_callback callback);
extern void anthropic_message_stream_with_tools(char* model, char* systemPrompt, char* userMessage, int maxTokens, char* toolsJSON, stream_callback callback);
extern void anthropic_agentic_loop(char* model, char* systemPrompt, char* userMessage, int maxTokens, char* toolsJSON, stream_callback callback, tool_executor toolExecutor);
extern void anthropic_free_string(char* s);

#ifdef __cplusplus
}
#endif
