//! Fixture data for panel previews
//!
//! Contains recorded data from real Palace sessions, used to render
//! realistic previews in the panel chooser dialog (Android ICS style).
//!
//! ## How fixtures are generated:
//!
//! 1. Run `palace capture-fixtures` to record a real AI session
//! 2. Session data is saved to `fixtures/session.json`
//! 3. Build process embeds this data via `include_str!`
//! 4. CI pipeline regenerates fixtures when UI changes
//!
//! The default fixture is an "Asteroids" implementation session.

use crate::state::SuggestionCard;
use serde::{Deserialize, Serialize};

/// Recorded fixture data from a real session
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RecordedFixtures {
    /// Version of the fixture format
    pub version: u32,
    /// When these fixtures were recorded (ISO 8601)
    pub recorded_at: String,
    /// Project name that was used
    pub project_name: String,
    /// Example suggestion cards
    pub cards: Vec<RecordedCard>,
    /// Tool log entries (timestamped)
    pub tool_log: Vec<String>,
    /// Thought log entries
    pub thought_log: Vec<String>,
    /// Analysis log entries
    pub analysis_log: Vec<String>,
    /// Example projects (for project chooser preview)
    pub projects: Vec<RecordedProject>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RecordedCard {
    pub id: usize,
    pub title: String,
    pub category: String,
    pub description: String,
    pub selected: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RecordedProject {
    pub name: String,
    pub path: String,
    pub languages: Vec<String>,
}

/// Example project for fixtures (legacy format, kept for compatibility)
pub struct FixtureProject {
    pub name: &'static str,
    pub path: &'static str,
    pub languages: &'static [&'static str],
}

// Embedded fixture data - generated by `palace capture-fixtures`
// If the file doesn't exist, we fall back to default inline data
const FIXTURE_JSON: Option<&str> = option_env!("PALACE_FIXTURES_JSON");

/// Load fixtures from embedded JSON or fall back to defaults
fn load_fixtures() -> RecordedFixtures {
    // Try to load from embedded JSON (set at build time)
    if let Some(json) = FIXTURE_JSON {
        if let Ok(fixtures) = serde_json::from_str(json) {
            return fixtures;
        }
    }

    // Try to load from file at runtime (for development)
    if let Ok(json) = std::fs::read_to_string("fixtures/session.json") {
        if let Ok(fixtures) = serde_json::from_str(&json) {
            return fixtures;
        }
    }

    // Fall back to default inline fixtures
    default_fixtures()
}

/// Default fixture data (used when no recorded session exists)
/// This is a manually-crafted example for the Asteroids implementation task
fn default_fixtures() -> RecordedFixtures {
    RecordedFixtures {
        version: 1,
        recorded_at: "2025-01-07T00:00:00Z".to_string(),
        project_name: "asteroids".to_string(),
        cards: vec![
            RecordedCard {
                id: 1,
                title: "Set up game window and render loop".to_string(),
                category: "setup".to_string(),
                description: "Initialize WGPU, create window with winit, 60fps render loop".to_string(),
                selected: true,
            },
            RecordedCard {
                id: 2,
                title: "Implement ship physics and controls".to_string(),
                category: "gameplay".to_string(),
                description: "Thrust, rotation, momentum, wrap-around edges".to_string(),
                selected: true,
            },
            RecordedCard {
                id: 3,
                title: "Create asteroid spawning system".to_string(),
                category: "gameplay".to_string(),
                description: "Spawn at edges, split when hit".to_string(),
                selected: false,
            },
            RecordedCard {
                id: 4,
                title: "Add bullet firing and collision".to_string(),
                category: "gameplay".to_string(),
                description: "Fire in ship direction, circle collision tests".to_string(),
                selected: false,
            },
            RecordedCard {
                id: 5,
                title: "Implement scoring and lives".to_string(),
                category: "ui".to_string(),
                description: "Score per asteroid, 3 lives, respawn".to_string(),
                selected: false,
            },
            RecordedCard {
                id: 6,
                title: "Add sound effects".to_string(),
                category: "polish".to_string(),
                description: "Thrust, lasers, explosions".to_string(),
                selected: false,
            },
        ],
        tool_log: vec![
            "[14:23:01] 📂 Read src/main.rs".to_string(),
            "[14:23:02] 🔍 Search 'winit'".to_string(),
            "[14:23:05] ✏️ Edit src/main.rs".to_string(),
            "[14:23:08] 📂 Read src/game/mod.rs".to_string(),
            "[14:23:10] ✏️ Create ship.rs".to_string(),
            "[14:23:15] ✏️ Edit ship.rs".to_string(),
            "[14:23:18] 🔨 cargo check".to_string(),
            "[14:23:22] ✅ Build OK".to_string(),
        ],
        thought_log: vec![
            "Looking at project structure...".to_string(),
            "Found winit in Cargo.toml.".to_string(),
            "Adding Ship struct with pos, vel.".to_string(),
            "Implementing thrust acceleration.".to_string(),
            "Screen wrap when x > width.".to_string(),
            "Increasing ROTATION_SPEED.".to_string(),
            "Build succeeded!".to_string(),
            "Adding momentum decay.".to_string(),
        ],
        analysis_log: vec![
            "📊 Analyzing project...".to_string(),
            "Found: Cargo.toml, src/".to_string(),
            "Deps: wgpu, winit, glam".to_string(),
            "🔍 Scanning for game logic...".to_string(),
            "No game module yet.".to_string(),
            "✅ Ready to implement.".to_string(),
        ],
        projects: vec![
            RecordedProject {
                name: "asteroids".to_string(),
                path: "/home/dev/asteroids".to_string(),
                languages: vec!["Rust".to_string()],
            },
            RecordedProject {
                name: "palace".to_string(),
                path: "/home/dev/palace".to_string(),
                languages: vec!["Rust".to_string()],
            },
            RecordedProject {
                name: "web-app".to_string(),
                path: "/home/dev/web-app".to_string(),
                languages: vec!["TypeScript".to_string()],
            },
            RecordedProject {
                name: "api".to_string(),
                path: "/home/dev/api".to_string(),
                languages: vec!["Go".to_string()],
            },
        ],
    }
}

// Cached fixtures (loaded once)
static FIXTURES: std::sync::OnceLock<RecordedFixtures> = std::sync::OnceLock::new();

fn get_fixtures() -> &'static RecordedFixtures {
    FIXTURES.get_or_init(load_fixtures)
}

/// Get fixture suggestion cards
pub fn fixture_suggestion_cards() -> Vec<SuggestionCard> {
    get_fixtures()
        .cards
        .iter()
        .map(|c| SuggestionCard {
            id: c.id,
            title: c.title.clone(),
            category: c.category.clone(),
            description: c.description.clone(),
            command: None,
            selected: c.selected,
            streaming: false,
        })
        .collect()
}

/// Fixture tool log entries
pub fn fixture_tool_log() -> Vec<String> {
    get_fixtures().tool_log.clone()
}

/// Fixture thought log entries
pub fn fixture_thought_log() -> Vec<String> {
    get_fixtures().thought_log.clone()
}

/// Fixture analysis log entries
pub fn fixture_analysis_log() -> Vec<String> {
    get_fixtures().analysis_log.clone()
}

/// Fixture projects for project chooser
pub fn fixture_projects() -> Vec<FixtureProject> {
    // Return static references by leaking the strings
    // This is fine since fixtures are loaded once and live forever
    get_fixtures()
        .projects
        .iter()
        .map(|p| {
            let name: &'static str = Box::leak(p.name.clone().into_boxed_str());
            let path: &'static str = Box::leak(p.path.clone().into_boxed_str());
            let languages: &'static [&'static str] = Box::leak(
                p.languages
                    .iter()
                    .map(|l| -> &'static str { Box::leak(l.clone().into_boxed_str()) })
                    .collect::<Vec<_>>()
                    .into_boxed_slice(),
            );
            FixtureProject { name, path, languages }
        })
        .collect()
}

/// Panel fixture enum for type-safe access
pub enum PanelFixture {
    QuestLog(Vec<SuggestionCard>),
    Execution {
        tool_log: Vec<String>,
        thought_log: Vec<String>,
    },
    Analysis(Vec<String>),
    ProjectChooser(Vec<FixtureProject>),
}

/// Get fixture data for a specific panel type
pub fn get_panel_fixture(panel_type: &str) -> Option<PanelFixture> {
    match panel_type {
        "quest_log" => Some(PanelFixture::QuestLog(fixture_suggestion_cards())),
        "execution" => Some(PanelFixture::Execution {
            tool_log: fixture_tool_log(),
            thought_log: fixture_thought_log(),
        }),
        "analysis" => Some(PanelFixture::Analysis(fixture_analysis_log())),
        "project_chooser" => Some(PanelFixture::ProjectChooser(fixture_projects())),
        _ => None,
    }
}

/// Capture session data for fixtures (called during recording)
#[derive(Debug, Default)]
pub struct FixtureCapture {
    pub cards: Vec<RecordedCard>,
    pub tool_log: Vec<String>,
    pub thought_log: Vec<String>,
    pub analysis_log: Vec<String>,
}

impl FixtureCapture {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn add_card(&mut self, card: &SuggestionCard) {
        self.cards.push(RecordedCard {
            id: card.id,
            title: card.title.clone(),
            category: card.category.clone(),
            description: card.description.clone(),
            selected: card.selected,
        });
    }

    pub fn add_tool(&mut self, entry: String) {
        self.tool_log.push(entry);
    }

    pub fn add_thought(&mut self, entry: String) {
        self.thought_log.push(entry);
    }

    pub fn add_analysis(&mut self, entry: String) {
        self.analysis_log.push(entry);
    }

    /// Export captured data to JSON
    pub fn export(&self, project_name: &str) -> Result<String, serde_json::Error> {
        use std::time::{SystemTime, UNIX_EPOCH};
        let timestamp = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .map(|d| d.as_secs())
            .unwrap_or(0);

        let fixtures = RecordedFixtures {
            version: 1,
            recorded_at: format!("{}", timestamp), // Unix timestamp, convert to ISO 8601 externally if needed
            project_name: project_name.to_string(),
            cards: self.cards.clone(),
            tool_log: self.tool_log.clone(),
            thought_log: self.thought_log.clone(),
            analysis_log: self.analysis_log.clone(),
            projects: vec![], // Projects are discovered, not captured
        };
        serde_json::to_string_pretty(&fixtures)
    }

    /// Save captured data to file
    pub fn save(&self, project_name: &str, path: &str) -> Result<(), Box<dyn std::error::Error>> {
        let json = self.export(project_name)?;
        std::fs::create_dir_all(std::path::Path::new(path).parent().unwrap_or(std::path::Path::new(".")))?;
        std::fs::write(path, json)?;
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_fixture_cards_not_empty() {
        let cards = fixture_suggestion_cards();
        assert!(!cards.is_empty());
        assert!(cards.len() >= 4);
    }

    #[test]
    fn test_fixture_logs_not_empty() {
        assert!(!fixture_tool_log().is_empty());
        assert!(!fixture_thought_log().is_empty());
        assert!(!fixture_analysis_log().is_empty());
    }

    #[test]
    fn test_get_panel_fixture() {
        assert!(get_panel_fixture("quest_log").is_some());
        assert!(get_panel_fixture("execution").is_some());
        assert!(get_panel_fixture("analysis").is_some());
        assert!(get_panel_fixture("project_chooser").is_some());
        assert!(get_panel_fixture("invalid").is_none());
    }

    #[test]
    fn test_fixture_capture() {
        let mut capture = FixtureCapture::new();
        capture.add_tool("[00:00:00] Test".to_string());
        capture.add_thought("Thinking...".to_string());

        let json = capture.export("test-project").unwrap();
        assert!(json.contains("test-project"));
        assert!(json.contains("Test"));
    }
}
